### ISSUE TITLE
When in-game time ends,timer goes automatically to 60 minutes and game doesn't end

### ISSUE THREAD

**Issue by Saxavlax001** [GamakCZ/SkyWars-Pro#11]
![Screenshot_2020-02-08-15-06-53-853_com mojang minecraftpe](https://user-images.githubusercontent.com/22281205/74479076-3f86c500-4eb7-11ea-8dea-f352799cbc25.jpg)
I used again the latest clean version of skywars pro.

**Comment by Saxavlax001** [comment]
Make the game have a draw,so no one will win in game if the certain time ends.

**Comment by GamakCZ** [comment]
Thx for report. In next version it's fixed.

**Comment by Saxavlax001** [comment]
Ok great
