### ISSUE TITLE
Error crash server

### ISSUE THREAD

**Issue by Centoller** [GamakCZ/SkyWars-Pro#17]
the server closes when starting a game and teleports to the arena lobby 

`Error: include(phar:///home/gs-41147/plugins/SkyWars_v0.1.phar/src/SW/Others/Funciones.php): failed to open stream: phar error: 
Server Details
Files
    Cannot open phar archive "/home/gs-41147/plugins/SkyWars_v0.1.phar" for reading
File: vendor/pocketmine/classloader/src/BaseClassLoader
Line: 138
Advanced Settings
Console
Type: ErrorException
Players
A PLUGIN WAS INVOLVED IN THIS CRASH
Players
Code:
Online
Scheduler
[129]    * Called when there is a class to load
Scheduler
[130]    *
[131]    * @param string $name
Operators
Schedules
Server Page
[132]    *
[133]    * @return bool
[134]    */
White List
Automatic Restart
FTP
[135]   public function loadClass($name){
[136]       $path = $this->findClass($name);
[137]       if($path !== null){
Ban List
MySQL
[138]           include($path);
[139]           if(!class_exists($name, false) and !interface_exists($name, false) and !trait_exists($name, false)){
[140]               return false;
Backups
[141]           }
[142] 
[143]           if(method_exists($name, "onClassLoaded") and (new ReflectionClass($name))->getMethod("onClassLoaded")->isStatic
Error Log
    ()){
[144]               $name::onClassLoaded();
Reinstall
[145]           }
[146]           
[147]           $this->classes[] = $name;
[148] 
Backtrace:
#0 vendor/pocketmine/classloader/src/BaseClassLoader(138): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string[200] 
    include(phar:///home/gs-41147/plugins/SkyWars_v0.1.phar/src/SW/Others/Funciones., string[98] phar:///home/gs-41147
    /PocketMine-MP (2).phar/vendor/pocketmine/classloader/src/B, integer 138, array[2])
#1 vendor/pocketmine/classloader/src/BaseClassLoader(138): include()
#2 vendor/pocketmine/classloader/src/BaseClassLoader(124): BaseClassLoader->loadClass(string[19] SW\Others\Funciones)
#3 (): BaseClassLoader->{closure}(string[19] SW\Others\Funciones)
#4 plugins/SkyWars_v0.1.phar/src/SW/Base(53): spl_autoload_call(string[19] SW\Others\Funciones)
#5 plugins/SkyWars_v0.1.phar/src/SW/Base(365): SW\Base->kits()
#6 plugins/SkyWars_v0.1.phar/src/SW/Task/GameTask(46): SW\Game->start()
#7 src/pocketmine/scheduler/TaskHandler(134): SW\Task\GameTask->onRun(integer 197021)
#8 src/pocketmine/scheduler/TaskScheduler(176): pocketmine\scheduler\TaskHandler->run(integer 197021)
#9 src/pocketmine/plugin/PluginManager(643): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 197021)
#10 src/pocketmine/Server(2379): pocketmine\plugin\PluginManager->tickSchedulers(integer 197021)
#11 src/pocketmine/Server(2142): pocketmine\Server->tick()
#12 src/pocketmine/Server(1989): pocketmine\Server->tickProcessor()
#13 src/pocketmine/Server(1583): pocketmine\Server->start()
#14 src/pocketmine/PocketMine(274): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, 
    string[15] /home/gs-41147/, string[23] /home/gs-41147/plugins/)
#15 src/pocketmine/PocketMine(297): pocketmine\server()
#16 (11): require(string[74] phar:///home/gs-41147/PocketMine-MP (2).phar/src/pocketmine/PocketMine.php)
PocketMine-MP version: 3.11.5 [Protocol 389]
Git commit: 13e4772f98fe665cc60ad2a2d2cde0eaaf1321b4-dirty
uname -a: Linux b7f84032452e 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64`

**Comment by GamakCZ** [comment]
This is not skywars pro
