### ISSUE TITLE
Crash Server Skywars v1.1.0 PRO

### ISSUE THREAD

**Issue by Centoller** [GamakCZ/SkyWars-Pro#18]
the server closes when entering the skywars and being teleported to the lobby 

`THIS CRASH WAS CAUSED BY A PLUGIN
Players
BAD PLUGIN: SkyWars v1.1.0 PRO [Codename Barrier]
Players
Code:
Online
Scheduler
[538]         if($this->inGame($player)) {
Scheduler
[539]             if(!$this->scheduler->teleportPlayers || $this->scheduler->startTime <= 5) {
[540]                 $index = null;
Operators
Schedules
Server Page
[541]                 foreach ($this->players as $i => $p) {
[542]                     if($p->getId() == $player->getId()) {
[543]                         $index = $i;
White List
Automatic Restart
FTP
[544]                     }
[545]                 }
[546] 
Ban List
MySQL
[547]                 if($event->getPlayer()->asVector3()->distance(Vector3::fromString($this->data["spawns"][$index])->add(0.5
    , 0, 0.5)) > 1) {
[548]                     // $event->setCancelled() will not work
Backups
[549]                     $player->teleport(Vector3::fromString($this->data["spawns"][$index])->add(0.5, 0, 0.5));
[550]                 }
[551]             }
Error Log
[552]         }
[553]     }
Reinstall
[554] 
[555]     /**
[556]      * @param PlayerExhaustEvent $event
[557]      */
Backtrace:
#0 plugins/SkyWars.phar/src/vixikhd/skywars/arena/Arena(547): pocketmine\utils\Utils::errorExceptionHandler(integer 8, 
    string[19] Undefined offset: 0, string[78] phar:///home/gs-41147/plugins/SkyWars.phar/src/vixikhd/skywars/arena/Arena.php, 
    integer 547, array[5])
#1 src/pocketmine/plugin/MethodEventExecutor(42): vixikhd\skywars\arena\Arena->onMove(object 
    pocketmine\event\player\PlayerMoveEvent)
#2 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object 
    vixikhd\skywars\arena\Arena, object pocketmine\event\player\PlayerMoveEvent)
#3 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object 
    pocketmine\event\player\PlayerMoveEvent)
#4 src/pocketmine/Player(1591): pocketmine\event\Event->call()
#5 src/pocketmine/Player(1699): pocketmine\Player->processMovement(integer 1)
#6 src/pocketmine/level/Level(841): pocketmine\Player->onUpdate(integer 1062863)
#7 src/pocketmine/level/Level(774): pocketmine\level\Level->actuallyDoTick(integer 1062863)
#8 src/pocketmine/Server(2255): pocketmine\level\Level->doTick(integer 1062863)
#9 src/pocketmine/Server(2386): pocketmine\Server->checkTickUpdates(integer 1062863, double 1582674516.0724)
#10 src/pocketmine/Server(2142): pocketmine\Server->tick()
#11 src/pocketmine/Server(1989): pocketmine\Server->tickProcessor()
#12 src/pocketmine/Server(1583): pocketmine\Server->start()
#13 src/pocketmine/PocketMine(274): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, 
    string[15] /home/gs-41147/, string[23] /home/gs-41147/plugins/)
#14 src/pocketmine/PocketMine(297): pocketmine\server()
#15 (11): require(string[74] phar:///home/gs-41147/PocketMine-MP (2).phar/src/pocketmine/PocketMine.php)
PocketMine-MP version: 3.11.5 [Protocol 389]
Git commit: 13e4772f98fe665cc60ad2a2d2cde0eaaf1321b4-dirty
uname -a: Linux 14b50604d336 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64
PHP Version: 7.3.7
Zend version: 3.3.7
OS : Linux, linux`

**Comment by GamakCZ** [comment]
Already fixed, I sent working version to email.
