### ISSUE TITLE
only op can put blocks

### ISSUE THREAD

**Issue by Centoller** [GamakCZ/SkyWars-Pro#21]
it occurred to me that only OPs allow them to put blocks in the skywars maps, the rest works correctly, I leave you an example video,
Video: 
https://youtu.be/XvCVLpw7uBs

 I have a separate host so it should not cause incompatibility problems with plugins, If you open chests like this that no protection plugin affects it, The spawn protection is 0 in server.properties

the version of the Plugin is: Skywars v1.1.0 PRO (Codename Barrier) 
The version of pocketmine is: 3.11.6

**Comment by GamakCZ** [comment]
That isn't caused by SkyWars. You have enabled spawn protection in server.properties. Set it to -1 to disable.
