### ISSUE TITLE
Your store is not working.

### ISSUE THREAD

**Issue by MrCyjaneK** [GamakCZ/SkyWars-Pro#6]
I'd like to purchase DEV 2 version, but I can't because your shop is not working.

**Comment by GamakCZ** [comment]
Thx for report.

**Comment by MrCyjaneK** [comment]
Also, I've emailed you. I don't know if you have received it so please send me message via https://contact.mrcyjanek.net, so I can contact you back.

**Comment by GamakCZ** [comment]
New store link [here](https://store.vixikhd.gq)
