### ISSUE TITLE
I can not pay

### ISSUE THREAD

**Issue by Centoller** [GamakCZ/SkyWars-Pro#8]
I can't buy the plugin from the page because it tells me "Billing Town / City is a required field." and I try to pay from paypal

**Comment by GamakCZ** [comment]
This says paypal or the store?

**Comment by GamakCZ** [comment]
I cannot reproduce that

**Comment by Centoller** [comment]
So how will I buy the plugin?

**Comment by GamakCZ** [comment]
could you please send me screenshots?

**Comment by GamakCZ** [comment]
Try buying it using shopping cart

**Comment by GamakCZ** [comment]
I think it's fixed.
